import 'bootstrap/scss/bootstrap.scss';
import "./hoc/spacing-controls/script";
import "./animate/style.scss";
import "./nav/style.scss";
import './blocks/grid/script';
import './blocks/text/script';
import './blocks/button/script';
import './blocks/title/script';
import './blocks/image/script';
import $ from 'jquery';